create schema if not exists traffic_limits;
create table if not exists traffic_limits.limits_per_hour (
    id bigint not null unique generated by default as identity,
    limit_name varchar(3) not null,
    limit_value bigint not null,
    effective_date timestamp not null,
    primary key(id)
);
insert into traffic_limits.limits_per_hour(limit_name, limit_value, effective_date) VALUES ('min', 1024, current_timestamp);
insert into traffic_limits.limits_per_hour(limit_name, limit_value, effective_date) VALUES ('max', 1073741824, current_timestamp);